# Generated by Django 4.1 on 2022-08-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de_colis', models.CharField(max_length=255)),
                ('type_colis', models.CharField(max_length=255)),
                ('description_colis', models.TextField()),
                ('code_colour_colis', models.CharField(max_length=255)),
                ('package_colour_colis', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('status_payment', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=3, max_digits=6)),
                ('adresse_livrasion', models.CharField(max_length=255)),
                ('adresse_livrasion_latitude', models.CharField(max_length=255)),
                ('adresse_livrasion_longitude', models.CharField(max_length=255)),
                ('point_de_livraison', models.TextField()),
                ('point_de_livraison_longitude', models.TextField()),
                ('point_de_livraison_latitude', models.TextField()),
                ('code_colis', models.CharField(blank=True, default='', max_length=255)),
                ('nom_de_destination', models.TextField()),
                ('current_position_latitude', models.TextField()),
                ('current_position_longitude', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_user', to='Users.user_profile')),
            ],
        ),
    ]
