# Generated by Django 4.1 on 2022-08-13 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Image Profile')),
                ('type_piece', models.CharField(choices=[('PA', 'Passeport'), ('CI', "Carte D'identité")], max_length=255)),
                ('numero_piece', models.PositiveIntegerField()),
                ('image_piece_reto', models.ImageField(upload_to='Image Reto')),
                ('image_piece_verso', models.ImageField(upload_to='Image Verso')),
                ('Adresse', models.CharField(max_length=255)),
                ('type_user', models.CharField(choices=[('AD', 'Admin'), ('V', 'Vendeur'), ('L', 'Livreur'), ('C', 'Client')], max_length=255)),
                ('secret_code', models.CharField(blank=True, default='', max_length=255)),
                ('isactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
