# Generated by Django 4.1 on 2022-08-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='secret_code',
        ),
    ]
